version: "3.7"
services:
  postgres:
    image: postgres:13.4
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: "redis:7.0.10-alpine"
    ports:
      - "6379:6379"

  # Redis cluster
  redis-cluster:
    image: "bitnami/redis-cluster:7.0.10"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_NODES: "redis-cluster redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2 redis-cluster-node-3 redis-cluster-node-4"
      REDIS_CLUSTER_CREATOR: "yes"
      REDIS_CLUSTER_REPLICAS: "1"
    ports:
      - "6380:6379"
    depends_on:
      - redis-cluster-node-0
      - redis-cluster-node-1
      - redis-cluster-node-2
      - redis-cluster-node-3
      - redis-cluster-node-4

  redis-cluster-node-0:
    image: "bitnami/redis-cluster:7.0.10"
    ports:
      - "6381:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_NODES: "redis-cluster redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2 redis-cluster-node-3 redis-cluster-node-4"

  redis-cluster-node-1:
    image: "bitnami/redis-cluster:7.0.10"
    ports:
      - "6382:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_NODES: "redis-cluster redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2 redis-cluster-node-3 redis-cluster-node-4"

  redis-cluster-node-2:
    image: "bitnami/redis-cluster:7.0.10"
    ports:
      - "6383:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_NODES: "redis-cluster redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2 redis-cluster-node-3 redis-cluster-node-4"

  redis-cluster-node-3:
    image: "bitnami/redis-cluster:7.0.10"
    ports:
      - "6384:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_NODES: "redis-cluster redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2 redis-cluster-node-3 redis-cluster-node-4"

  redis-cluster-node-4:
    image: "bitnami/redis-cluster:7.0.10"
    ports:
      - "6385:6379"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_NODES: "redis-cluster redis-cluster-node-0 redis-cluster-node-1 redis-cluster-node-2 redis-cluster-node-3 redis-cluster-node-4"

  rabbitmq:
    image: rabbitmq:3.11.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "xivs"
      RABBITMQ_DEFAULT_PASS: "xivs"
      RABBITMQ_PLUGINS_DIR: "/opt/rabbitmq/plugins:/usr/lib/rabbitmq/plugins"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbit/plugins:/usr/lib/rabbitmq/plugins

volumes:
  postgres-data:
  rabbitmq_data:
