[package]
name = "svix"
version = "1.5.2"
authors = ["Svix Inc. <oss@svix.com>"]
edition = "2021"
description="Rust library for interacting with the Svix API and verifying webhook signatures."
homepage="https://www.svix.com"
repository="https://github.com/svix/svix-webhooks"
readme="../README.md"
license="MIT"
keywords=["svix", "webhooks", "diahook"]
categories = ["development-tools", "asynchronous", "network-programming", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac-sha256 = "1"
base64 = "0.13"
time = "0.3"
thiserror = ">1.0.30"
http = "0.2"

# API stuff
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "^2.2"
reqwest = { version = "^0.11", features = ["json", "multipart"], default-features = false }

[features]
default = ["reqwest/default-tls"]
rustls-tls = ["reqwest/rustls-tls"]
