[package]
name = "svix-server"
version = "0.73.0"
license = "MIT"
description = "Svix webhooks server"

authors = ["Svix Inc. <oss@svix.com>"]
homepage = "https://www.svix.com"
repository = "https://github.com/svix/svix-webhooks"
readme = "../README.md"
edition = "2021"
publish = false

[dependencies]
svix-server_derive = { path = "../svix-server_derive" }

svix = "0.60"
svix-ksuid = "^0.5.1"
dotenv = "0.15.0"
sha2 = "0.10.2"
hmac-sha256 = "1"
clap = { version = "3.2.1", features = ["derive"] }
axum = { version = "0.6.1", features = ["headers"] }
base64 = "0.13.0"
hyper = { version = "0.14.16", features = ["full"] }
tokio = { version = "1.15.0", features = ["full"] }
tower = "0.4.11"
tower-http = { version = "0.3.4", features = ["trace", "cors", "request-id"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
serde_urlencoded = "0.7.1"
serde_path_to_error = "0.1.7"
num_enum = "0.5.6"
enum_dispatch = "0.3.8"
regex = "1.5.5"
lazy_static = "1.4.0"
figment = { version = "0.10", features = ["toml", "env", "test"] }
tracing = "0.1.35"
tracing-subscriber = { version="0.3", features = ["env-filter", "json"] }
tracing-opentelemetry = "0.17.3"
opentelemetry = { version= "0.17", features = ["rt-tokio"] }
opentelemetry-http = "0.6.0"
opentelemetry-otlp = { version = "0.10" }
validator = { version = "0.14.0", features = ["derive"] }
jwt-simple = "0.10.8"
ed25519-compact = "1.0.11"
chrono = { version="0.4.19", features = ["serde"] }
reqwest = { version = "0.11.9", features = ["json", "rustls-tls", "trust-dns"], default-features = false }
bb8 = "0.7.1"
bb8-redis = "0.10.1"
redis = { version = "0.21.5", features = ["tokio-comp", "tokio-native-tls-comp", "streams"] }
thiserror = "1.0.30"
bytes = "1.1.0"
blake2 = "0.10.4"
chacha20poly1305 = "0.9.0"
# sea orm
sea-orm = { version = "0.10.2", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono", "with-json" ], default-features = false }
sqlx = { version = "0.6.2", features = [ "runtime-tokio-rustls", "postgres", "migrate" ] }
http = "0.2"
time = { version = "0.3.9", features = [ "std" ]}
futures = "0.3"
redis_cluster_async = { git = "https://github.com/redis-rs/redis-cluster-async.git", rev = "e6fe168" }
url = "2.2.2"
rand = "0.8.5"
jsonschema = "0.16.1"

[dev-dependencies]
anyhow = "1.0.56"
