name: Java Lint
on:
  pull_request:
    paths:
      - "java/**"
      - "openapi.json"
jobs:
  dotnet:
    name: Java Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
  
      - name: Regen openapi libs
        run: |
          yarn
          ./regen_openapi.sh
  
      - name: Build
        run: |
          cd java
          ./gradlew build
