name: Kotlin Lint
on:
  pull_request:
    paths:
      - "kotlin/**"
      - "openapi.json"
jobs:
  kotlin:
    name: Kotlin Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Regen openapi libs
        run: |
          yarn
          ./regen_openapi.sh

      - name: Build
        run: |
          cd kotlin
          ./gradlew build -x test
