name: Python Lint
on: 
  pull_request:
    paths:
      - "python/**"
      - "openapi.json"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          cd python
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt .
          python -m pip install -r requirements-dev.txt .

      - name: Regen openapi libs
        run: |
          cd python
          ./scripts/generate_openapi.sh

      - name: Run linting
        run: |
          cd python
          sh ./scripts/lint.sh
